true_review/models.py
from true_review import db


class Movies(db.Model):
    __tablename__ = 'movies'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    code = db.Column(db.Integer, nullable=True, unique=True)
    create_date = db.Column(db.DateTime(), nullable=False)
    image_path = db.Column(db.Text(), nullable=True)
    score = db.Column(db.Float, nullable=True)
    review_score = db.Column(db.Float, nullable=True)
    db.UniqueConstraint('id', 'code')

    reviews = db.relationship(
        "Reviews", backref=db.backref('movie', order_by=id))

    def __init__(self, title, code, create_date, image_path, score):
        self.title = title
        self.code = code
        self.create_date = create_date
        self.image_path = image_path
        self.score = score


class Reviews(db.Model):
    __tablename__ = 'reviews'

    id = db.Column(db.Integer, primary_key=True)
    movie_id = db.Column(db.Integer, db.ForeignKey(
        'movies.id', ondelete='CASCADE'))
    text_rank = db.Column(db.Float, nullable=True)
    content = db.Column(db.Text(), nullable=False)
    pos_or_neg = db.Column(db.Boolean, nullable=False)
    reviews = db.relationship('Movies', backref=db.backref('review_set'))

    def __init__(self, movie_id, text_rank, content, pos_or_neg):
        self.movie_id = movie_id
        self.text_rank = text_rank
        self.content = content
        self.pos_or_neg = pos_or_neg


class Comments(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    movie_id = db.Column(db.Integer, db.ForeignKey(
        'movies.id', ondelete='CASCADE'))
    content = db.Column(db.Text(), nullable=False)
    movie_rating = db.Column(db.Integer, nullable=False)
    create_date = db.Column(db.DateTime(), nullable=False)
    emotion_percent = db.Column(db.Float, nullable=True)
    pos_or_neg = db.Column(db.Boolean, nullable=True)
    movie = db.relationship('Movies', backref=db.backref('comment_set'))

    def __init__(self, movie_id, content, movie_rating, create_date, emotion_percent, pos_or_neg):
        self.movie_id = movie_id
        self.content = content
        self.movie_rating = movie_rating
        self.create_date = create_date
        self.emotion_percent = emotion_percent
        self.pos_or_neg = pos_or_neg

true_review/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextField
from wtforms.validators import DataRequired, Length


class CommentForm(FlaskForm):
    """
    comment form which has validator
    """
    content = TextField('내용', validators=[Length(
        min=20, max=330, message="Comment must be between %(min)d and %(max)d characters")])

true_review/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
import config

db = SQLAlchemy()
migrate = Migrate()


def create_app():
    """
    start true_review app
    """
    app = Flask(__name__)

    app.config.from_object(config)

    db.init_app(app)
    migrate.init_app(app, db)
    from . import models

    from .views import main_views, movies_views, comment_views
    app.register_blueprint(main_views.bp)
    app.register_blueprint(movies_views.bp)
    app.register_blueprint(comment_views.bp)

    return app

true_review/views/comment_views.py
from datetime import datetime
from flask import Blueprint, url_for, request, render_template
from werkzeug.utils import redirect
from true_review import db
from true_review.models import Comments, Movies, Reviews
from true_review.forms import CommentForm
import requests as req
import json
import os

bp = Blueprint('comment', __name__, url_prefix='/comment')


@bp.route('/get_and_analysis/<int:movie_id>', methods=('GET', 'POST'))
def get_and_analysis(movie_id):
    """
    get comment and analysis it to get its emotion(positive/negative) and star rating by model.
    :return rendering movie_detail page differently wheather or not the valid comment is saved.
    """
    movie = Movies.query.get_or_404(movie_id)
    review_list = Reviews.query.filter_by(
        movie_id=movie.id).order_by(Reviews.text_rank.desc())
    form = CommentForm()
    if request.method == 'POST' and form.validate_on_submit():
        response = req.post(os.environ.get("API_SERVER"),
                            data={'text': form.content.data}).json()
        emotion_percent = response['emotion_percent']
        movie_rating = response['movie_rating']
        pos_or_neg = response['pos_or_neg']

        comment = Comments(movie_id=movie_id, content=form.content.data,
                           movie_rating=movie_rating, create_date=datetime.now(), emotion_percent=emotion_percent, pos_or_neg=pos_or_neg)
        movie.comment_set.append(comment)
        db.session.commit()
        return render_template('movies/movie_detail.html', movie=movie, form=form, isFirstRender=0, review_list=review_list, comment=comment)
    return render_template('movies/movie_detail.html', movie=movie, form=form, isFirstRender=1, review_list=review_list, comment=None)

true_review/views/main_views.py
from flask import Blueprint, render_template, url_for
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from werkzeug.utils import redirect
import config
from true_review.models import Movies
from true_review.update import update_movies_and_reviews


bp = Blueprint('main', __name__, url_prefix='/')


@bp.route('/update')
def update():
    """
    update movies and reviews from 'ranked_reviews' folder
    :return redirect to movie_.list
    """
    update_movies_and_reviews()
    return redirect(url_for('movies._list'))


@bp.route('/')
def index():
    """
    :return redirect to movies._list
    """
    return redirect(url_for('movies._list'))

true_review/views/movies_views.py
from flask import Blueprint, render_template, url_for
from werkzeug.utils import redirect
from true_review.models import Movies, Reviews
from .. import db
from werkzeug.utils import redirect
import requests
from true_review.forms import CommentForm

bp = Blueprint('movies', __name__, url_prefix='/movies')


@bp.route('/movie/<int:movie_code>/<int:isFirstRender>/')
def movie(movie_code: int, isFirstRender: int):
    """
    rendering movie_detail page which is selected in movie_list page
    :param  movie_code:     movie identify code from naver movie page
            isFirstRender:  0 if comment is not saved or 1
    """
    movie = db.session.query(Movies).filter_by(code=movie_code).first()
    if not movie:
        return redirect(url_for('movies._list'))
    review_list = Reviews.query.filter_by(
        movie_id=movie.id).order_by(Reviews.text_rank.desc())
    form = CommentForm()
    return render_template('movies/movie_detail.html', movie=movie, form=form, isFirstRender=isFirstRender, review_list=review_list, comment=None)


@bp.route('/list/')
def _list():
    """
    rendering movie_list page
    """
    movie_list = Movies.query.order_by(Movies.create_date.desc())
    return render_template('movies/movie_list.html', movie_list=movie_list)

true_review/templates/movies/movie_detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta
      name="author"
      content="Mark Otto, Jacob Thornton, and Bootstrap contributors"
    />
    <meta name="generator" content="Jekyll v4.1.1" />
    <title>{{ movie.title}}</title>

    <!-- Bootstrap core CSS -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='bootstrap.css') }}"
    />
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      .ratings {
        position: relative;
        vertical-align: middle;
        display: inline-block;
        color: #b1b1b1;
        overflow: hidden;
      }

      .full-stars {
        position: absolute;
        left: 0;
        top: 0;
        white-space: nowrap;
        overflow: hidden;
        color: #fde16d;
      }

      .empty-stars:before,
      .full-stars:before {
        content: "\2605\2605\2605\2605\2605";
        font-size: 14pt;
      }

      .empty-stars:before {
        -webkit-text-stroke: 1px #848484;
      }

      .full-stars:before {
        -webkit-text-stroke: 1px orange;
      }

      /* Webkit-text-stroke is not supported on firefox or IE */
      /* Firefox */
      @-moz-document url-prefix() {
        .full-stars {
          color: #ecbe24;
        }
      }
      .test {
        position: "absolute";
        height: "300px";
        width: "auto";
      }

      @media (max-width: 1000px) {
        .test {
          position: "center";
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link
      href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900"
      rel="stylesheet"
    />
    <!-- Star rating icon -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <!-- Custom styles for this template -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='blog.css') }}"
    />

    <script>
      showHideFlag = 0;

      window.onload = function hide() {
        if (showHideFlag == 0) {
          document.getElementById("showHide").style.display = "none";
        } else {
          document.getElementById("showHide").style.display = "block";
        }
      };
    </script>
  </head>

  <body>
    <div class="container">
      <div
        class="p-4 p-md-5 text-black rounded"
        style="
          margin-bottom: 0;
          padding: 0 !important;
          background-color: #34558b;
        "
      >
        <div class="col-md-12 px-0">
          <div class="row">
            <div class="col-md-4">
              <img
                src="{{ movie.image_path }}"
                height="340px"
                width="auto"
                style="display: block; margin: 0 auto"
              />
              <!--<img src="{{ movie.image_path }}" class="test" />-->
            </div>
            <div class="col-md-8" style="padding-bottom: 20px">
              <!-- <h1 class="display-4 font-italic" style="text-align: left">
                <br />
              </h1> -->
              <div
                class="display-3"
                style="
                  font-family: 'Helvetica Neue';
                  text-align: center;
                  color: white;
                "
              >
                "{{ movie.title }}"
              </div>
              <div
                class="display-4"
                style="
                  font-family: 'Helvetica Neue';
                  text-align: center;
                  color: white;
                "
              >
                분석 결과 입니다.
                <br />
              </div>
            </div>
          </div>
        </div>
      </div>
      <br />
      <div class="row">
        <div class="col-md-1" style="text-align: right">
          <img src="/static/naver.png" />
        </div>
        <div class="col-md-2" style="text-align: center">
          <div style="font-family: 'Helvetica Neue'; color: black">
            {{movie.score}} / 10.0
          </div>
          <div class="ratings">
            <div class="empty-stars"></div>
            <div
              class="full-stars"
              style="width: {{ movie.score * 10 }}%"
            ></div>
          </div>
          <br />
        </div>
        <div class="col-md-1" style="text-align: center">
          <img
            src="https://fontmeme.com/permalink/200910/109ba0996778b6d9b99ce3ec7deee89e.png"
            width="123px"
            height="31px"
            style="display: inline"
          />
        </div>
        <div class="col-md-2" style="text-align: center">
          <div style="font-family: 'Helvetica Neue'; color: black">
            {{movie.review_score}} / 10.0
          </div>
          <div class="ratings">
            <div class="empty-stars"></div>
            <div
              class="full-stars"
              style="width: {{ movie.review_score * 10 }}%"
            ></div>
          </div>
        </div>
      </div>

      <div class="row mb-2">
        <div class="col-md-6">
          <div
            class="row no-gutters border rounded flex-md-row mb-4 shadow-sm h-md-250 overflow-auto position-relative"
          >
            <div class="col p-4 d-flex flex-column position-static">
              <h3 class="d-inline-block mb-2 text-primary">긍정 대표 리뷰</h3>
              <ol>
                {% for review in review_list %} {% if review.pos_or_neg == True
                %}
                <li>{{ review.content }}</li>
                <br />
                {% endif %} {% endfor %}
              </ol>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div
            class="row no-gutters border rounded overflow-auto flex-md-row mb-4 shadow-sm h-md-250 position-relative"
          >
            <div class="col p-4 d-flex flex-column position-static">
              <h3 class="d-inline-block mb-2 text-danger">부정 대표 리뷰</h3>
              <ol>
                {% for review in review_list %} {% if review.pos_or_neg == False
                %}
                <li>{{ review.content }}</li>
                <br />
                {% endif %} {% endfor %}
              </ol>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <form
            class="Gripost-form my-3"
            action="{{ url_for('comment.get_and_analysis', movie_id=movie.id) }}"
            method="post"
          >
            {{ form.csrf_token }} {% for field, errors in form.errors.items() %}
            <div class="alert alert-danger" role="alert">
              <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
            </div>
            {% endfor %} {% if not form.errors.items()%} {% if isFirstRender ==
            0 %}
            <script>
              showHideFlag = 1;
            </script>
            {% endif %} {% endif %}
            <div class="form-group">
              <textarea
                class="col-md-12"
                name="content"
                id="content"
                rows="4"
                resize="none"
                placeholder="댓글 등록이 가능합니다. 당신의 리뷰를 추가해주세요!"
                display="inline"
              ></textarea>
            </div>
            <div class="float-right form-group">
              <div class="col-sm-10"></div>
              <button type="submit" class="btn btn-outline-primary">
                저장하기
              </button>
            </div>
          </form>
        </div>
      </div>
      <div id="showHide">
        <span class="bg-light"> 당신이 작성한 리뷰</span>
        <div
          class="row no-gutters border rounded flex-md-row mb-4 shadow-sm overflow-auto position-relative"
          style="height: 100px"
        >
          {{ comment.content }}
        </div>
        <div class="row">
          <div class="col-md-8">
            <div class="bg-light rounded">
              {% if comment == None %}
              <p class="comment-analaysis">
                당신은 영화 "{{ movie.title }}"에 대해 null % 긍정, null %
                부정의 마음을 표하셨습니다!
              </p>
              <br />
              {% else %}
              <p class="comment-analaysis">
                당신은 영화 "{{ movie.title }}"에 대해
                <br />
                {% if comment.pos_or_neg == 1 %}
                <span style="color: blue">
                  {{ '%0.2f' % (comment.emotion_percent) }} % 긍정</span
                >,

                <span style="color: red">
                  {{ '%0.2f' % (100 - comment.emotion_percent) }} % 부정</span
                >의 {% else %}
                <span style="color: blue">
                  {{ '%0.2f' % (100 - comment.emotion_percent) }} % 긍정</span
                >,
                <span style="color: red">
                  {{ '%0.2f' % (comment.emotion_percent) }} % 부정</span
                >의 {% endif %} 마음을 표하셨습니다!
              </p>
              {% endif %}
            </div>
          </div>
          <div class="col-md-4">
            <div class="bg-light rounded">
              {% for star in range(10) %} {% if comment == None %} {% else %} {%
              if star < comment.movie_rating %}
              <span class="fa fa-star checked" style="color: orange"></span>
              {% else %}
              <span class="fa fa-star"></span>
              {% endif %} {% endif %} {% endfor %}
              <br />
              <p class="font-italic" style="display: block">
                리뷰에서 추출한 평점: {{ comment.movie_rating }}점
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <footer class="blog-footer">
      <p>
        <a href="http://13.124.8.184:5000/movies/list/">
          <button type="button" class="btn btn-primary bg-ours">
            이전 페이지
          </button>
        </a>
        <a href="#">
          <button type="button" class="btn btn-primary bg-ours">위로</button>
        </a>
      </p>
      <p>
        by
        <a href="https://github.com/Gaepodong/automatic_tagging_review_ratings"
          >team gaepodong</a
        >
      </p>
    </footer>
  </body>
</html>

true_review/templates/movies/movie_list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta
      name="author"
      content="Mark Otto, Jacob Thornton, and Bootstrap contributors"
    />
    <meta name="generator" content="Jekyll v4.1.1" />
    <title>Your True Review</title>

    <!-- Bootstrap core CSS -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='bootstrap.css') }}"
    />

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link
      href="{{ url_for('static', filename='index.css') }}"
      rel="stylesheet"
    />
  </head>

  <body>
    <header>
      <div class="collapse bg-ours" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">
                <a
                  href="https://en.wikipedia.org/wiki/Sentiment_analysis"
                  class="text-black"
                  >'감정분석 및 textrank를 이용한 영화 대표리뷰 추출과 자동 평점
                  부여'</a
                >
                기능을 제공하여, 리뷰와 평점을 영화를 판단하는 신뢰할 수 있는
                지표로 활용할 수 있도록 돕는 서비스입니다.
              </p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Contact</h4>
              <ul class="list-unstyled">
                <li>
                  <a href="https://github.com/l-yohai" class="text-black"
                    >yohlee</a
                  >
                </li>
                <li>
                  <a href="https://github.com/simian114" class="text-black"
                    >sanam</a
                  >
                </li>
                <li>
                  <a href="https://github.com/KyungKyuLee" class="text-black"
                    >kylee</a
                  >
                </li>
                <li>
                  <a href="https://github.com/LeejwUniverse" class="text-black"
                    >jungwlee</a
                  >
                </li>
                <li>
                  <a href="https://github.com/humblEgo" class="text-black"
                    >iwoo</a
                  >
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-ours shadow-sm">
        <div class="container d-flex justify-content-between">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="20"
              height="20"
              fill="none"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              aria-hidden="true"
              class="mr-2"
              viewBox="0 0 24 24"
              focusable="false"
            >
              <path
                d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"
              />
              <circle cx="12" cy="13" r="4" />
            </svg>
            <strong>True Review</strong>
          </a>
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarHeader"
            aria-controls="navbarHeader"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main role="main">
      <section class="jumbotron text-center">
        <div class="container">
          <h1>Your True Review</h1>
          <p class="lead text-muted">별점 조작없는 영화리뷰를 만나보세요!</p>
        </div>
      </section>

      <div class="album py-5 bg-light">
        <div class="container">
          {% if movie_list %}
          <div class="row">
            {% for movie in movie_list %}
            <div class="col-md-4">
              <a href="/movies/movie/{{ movie.code }}/1/">
                <div class="card mb-4 shadow-sm">
                  <svg
                    class="bd-placeholder-img card-img-top"
                    width="100%"
                    height="400"
                    xmlns="http://www.w3.org/2000/svg"
                    preserveAspectRatio="xMidYMid slice"
                    focusable="false"
                    role="img"
                    aria-label="Placeholder: Thumbnail"
                  >
                    <title>Placeholder</title>
                    <rect width="100%" height="100%" fill="#ffffff" />
                    <image
                      xlink:href="{{ movie.image_path }}"
                      x="0"
                      y="0"
                      height="100%"
                      width="100%"
                    />
                  </svg>
                  <div class="card-body">
                    <p class="card-text">{{ movie.title }}</p>
                    <div
                      class="d-flex justify-content-between align-items-center"
                    >
                      <small class="text-muted">{{ movie.create_date }}</small>
                    </div>
                  </div>
                </div>
              </a>
            </div>
            {% endfor %} {% else %}
            <p>영화가 없습니다.</p>
          </div>
          {% endif %}
        </div>
      </div>
    </main>
    <footer class="blog-footer">
      <div class="container">
        <p style="text-align: center">
          <a href="#">
            <button type="button" class="btn btn-primary bg-ours">위로</button>
          </a>
        </p>
        <p style="text-align: center">
          by
          <a
            href="https://github.com/Gaepodong/automatic_tagging_review_ratings"
            >team gaepodong</a
          >
        </p>
      </div>
    </footer>
  </body>
  <script
    src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"
  ></script>
  <script>
    window.jQuery ||
      document.write(
        '<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>'
      );
  </script>
  <script src="{{ url_for('static', filename='bootstrap.bundle.min.js')}}"></script>
</html>